#!/bin/bash
# setup script to link to the new bash profile
# created by Ronald Jerez Ronald Jerez (github.com/ronaldjerez)

# the new profile is already setup
(($_COMMON_PROFILE_SET_)) && {
	style red "\n\nYour bash profile is already setup, exiting\n\n"
	exit
}

# location to script
profileScript="$(pwd)/profile.bash"

# the code to prepend to the .bash_profile
code="\\
# Available GIT PROMPT options\\
GIT_PROMPT_SHOW_DIRTY=1\\
GIT_PROMPT_SHOW_STASH=1\\
GIT_PROMPT_SHOW_AHEAD=1\\
GIT_PROMPT_SHOW_BEHIND=1\\
\\
# You can also change the default colors\\
# GIT_PROMPT_CLEAN_COLOR=green\\
# GIT_PROMPT_DIRTY_COLOR=red\\
# GIT_PROMPT_AHEAD_COLOR=\"light cyan\"\\
# GIT_PROMPT_BEHIND_COLOR=\"light black\"\\
\\
if [ -f $profileScript ]; then\\
	source $profileScript\\
fi\\
"
# add the hash bang to the code if its a new profile
[ ! -f ~/.bash_profile ] && code="#!/bin/bash\n$code"

# append the code to the bash profile
echo -ne "${code}" | tr -d "\\" >> ~/.bash_profile
source ~/.bash_profile
style light green "\n\nSetup complete, restart your terminal instance.\n\n"
