#!/bin/bash
# setup script to link to the new bash profile
# created by Ronald Jerez Ronald Jerez (github.com/ronaldjerez)

# the new profile is already setup
(($_COMMON_PROFILE_SET_)) && {
	printf "\n\n\e[0;31mYour bash profile is already setup, exiting\e[0m\n\n"
	exit
}

# location to script
profileScript="$(pwd)/profile.bash"

# the code to prepend to the .bash_profile
code="\\
# Available GIT PROMPT options\\
#GIT_PS1_SHOWDIRTYSTATE=1\\
#GIT_PS1_SHOWCOLORHINTS=1\\
#GIT_PS1_SHOWUNTRACKEDFILES=1\\
#GIT_PS1_SHOWSTASHSTATE=1\\
\\
if [ -f $profileScript ]; then\\
	source $profileScript\\
fi\\
"
# add the hash bang to the code if its a new profile
[ ! -f ~/.bash_profile ] && code="#!/bin/bash\n$code"

# append the code to the bash profile
echo -ne "${code}" | tr -d "\\" >> ~/.bash_profile
echo -ne "\n\n\e[0;31mSetup complete, restart your terminal instances\e[0m\n\n"